/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2026-02-03T16:36:51.722Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Joseph Bitton",
      photo: "https://app.salesgenius.co/api/user-images/056f1b9a-6e97-4cee-89c3-7bd9f9397ed3?v=06df1d5eab706552fcdffd5e1a78de0f66691b4a0c6513a22035b4b6d4bd2fef",
      phone: "4168018600",
      email: "josephbitton1@gmail.com",
      company: "Real Broker Ontario Ltd.",
      companyLogo: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768333675342-w1200_original_13dc3970-c036-43e0-8228-e0a6fb4270fa.png",
      companyAddress: "130 King ST W Unit 1900B Toronto, Ontario, M5X1E3",
      license: "REALTOR®",
      repo: "New-Listing-478"
    },
    social: {
      instagram: "https://www.instagram.com/josephbitton_realestate/",
      facebook: "https://www.facebook.com/torontorealestate4u/",
      linkedin: ""
    }
  };

// formAutomations configuration
export const formAutomations = {
    crmLeadParsingEmail: "",
    sgApiKey: ""
  };

// formQuestions configuration
export const formQuestions = [
    {
      id: 1,
      key: "buyingTimeline",
      question: "When are you looking to buy?",
      order: 1,
      options: [
        {
          value: "immediately",
          label: "Immediately",
          emoji: "🚀"
        },
        {
          value: "1-3months",
          label: "1-3 months",
          emoji: "📅"
        },
        {
          value: "3-6months",
          label: "3-6 months",
          emoji: "⏰"
        },
        {
          value: "6+months",
          label: "6+ months",
          emoji: "🔮"
        },
        {
          value: "just-exploring",
          label: "Just exploring",
          emoji: "👀"
        }
      ]
    },
    {
      id: 2,
      key: "propertyType",
      question: "What type of property interests you?",
      order: 2,
      options: [
        {
          value: "house",
          label: "Single Family Home",
          emoji: "🏠"
        },
        {
          value: "condo",
          label: "Condo/Apartment",
          emoji: "🏢"
        },
        {
          value: "townhouse",
          label: "Townhouse",
          emoji: "🏘️"
        },
        {
          value: "investment",
          label: "Investment Property",
          emoji: "💼"
        },
        {
          value: "any",
          label: "Open to anything",
          emoji: "✨"
        }
      ]
    }
  ];

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345703648-001_0_mc3yc00gq9wx665lup.jpg",
      alt: "Property image 1",
      category: ""
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345704688-002_14.jpeg",
      alt: "Property image 2",
      category: ""
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345705945-003_15.jpeg",
      alt: "Property image 3",
      category: ""
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345707061-004_01TT39.jpeg",
      alt: "Property image 4",
      category: ""
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345708255-005_02TT39.jpeg",
      alt: "Property image 5",
      category: ""
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345709127-006_10.jpg",
      alt: "Property image 6",
      category: ""
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345709931-007_11.jpg",
      alt: "Property image 7",
      category: ""
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345711007-008_13.jpg",
      alt: "Property image 8",
      category: ""
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345711375-009_9.jpg",
      alt: "Property image 9",
      category: ""
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345711768-010_03TT39.jpg",
      alt: "Property image 10",
      category: ""
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345712444-011_04TT39.jpg",
      alt: "Property image 11",
      category: ""
    },
    {
      id: 12,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345713113-012_05TT39.jpg",
      alt: "Property image 12",
      category: ""
    },
    {
      id: 13,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345713692-013_06202025_170154_2.jpg",
      alt: "Property image 13",
      category: ""
    },
    {
      id: 14,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345714419-014_07TT39.JPG",
      alt: "Property image 14",
      category: ""
    },
    {
      id: 15,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345715153-015_06202025_170311_2.jpg",
      alt: "Property image 15",
      category: ""
    },
    {
      id: 16,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345715747-016_06202025_170239_2.jpg",
      alt: "Property image 16",
      category: ""
    },
    {
      id: 17,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345716466-017_06202025_170334_2.jpg",
      alt: "Property image 17",
      category: ""
    },
    {
      id: 18,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345717025-018_10TT39.jpg",
      alt: "Property image 18",
      category: ""
    },
    {
      id: 19,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345717487-019_11TT39.jpg",
      alt: "Property image 19",
      category: ""
    },
    {
      id: 20,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345717970-020_09TT39.JPG",
      alt: "Property image 20",
      category: ""
    },
    {
      id: 21,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345718487-021_12TT39.jpg",
      alt: "Property image 21",
      category: ""
    },
    {
      id: 22,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345719123-022_13TT39.jpg",
      alt: "Property image 22",
      category: ""
    },
    {
      id: 23,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345719644-023_16TT39.jpg",
      alt: "Property image 23",
      category: ""
    },
    {
      id: 24,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345720070-024_17TT39.jpg",
      alt: "Property image 24",
      category: ""
    },
    {
      id: 25,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345720608-025_18TT39.jpg",
      alt: "Property image 25",
      category: ""
    },
    {
      id: 26,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345721118-026_19TT39.jpg",
      alt: "Property image 26",
      category: ""
    },
    {
      id: 27,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345721686-027_20TT39.jpg",
      alt: "Property image 27",
      category: ""
    },
    {
      id: 28,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345722409-028_21TT39.jpg",
      alt: "Property image 28",
      category: ""
    },
    {
      id: 29,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345722929-029_22TT39.jpg",
      alt: "Property image 29",
      category: ""
    },
    {
      id: 30,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345723449-030_23TT39.jpg",
      alt: "Property image 30",
      category: ""
    },
    {
      id: 31,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345723828-031_24TT39.jpg",
      alt: "Property image 31",
      category: ""
    },
    {
      id: 32,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345724275-032_25TT39.jpg",
      alt: "Property image 32",
      category: ""
    },
    {
      id: 33,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345724685-033_26TT39.jpg",
      alt: "Property image 33",
      category: ""
    },
    {
      id: 34,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345725141-034_27TT39.jpg",
      alt: "Property image 34",
      category: ""
    },
    {
      id: 35,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345725657-035_28TT39.jpg",
      alt: "Property image 35",
      category: ""
    },
    {
      id: 36,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345726080-036_29TT39.jpg",
      alt: "Property image 36",
      category: ""
    },
    {
      id: 37,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345726474-037_30TT39.jpg",
      alt: "Property image 37",
      category: ""
    },
    {
      id: 38,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345726863-038_31TT39.jpg",
      alt: "Property image 38",
      category: ""
    },
    {
      id: 39,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345727300-039_32TT39.JPG",
      alt: "Property image 39",
      category: ""
    },
    {
      id: 40,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345727780-040_33TT39.JPG",
      alt: "Property image 40",
      category: ""
    },
    {
      id: 41,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345728287-041_36TT39.JPG",
      alt: "Property image 41",
      category: ""
    },
    {
      id: 42,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345729084-042_37TT39.JPG",
      alt: "Property image 42",
      category: ""
    },
    {
      id: 43,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345730070-043_38TT39.JPG",
      alt: "Property image 43",
      category: ""
    },
    {
      id: 44,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345731022-044_39TT39.JPG",
      alt: "Property image 44",
      category: ""
    },
    {
      id: 45,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345731944-045_35TT39.jpeg",
      alt: "Property image 45",
      category: ""
    },
    {
      id: 46,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345732450-046_34TT39.jpeg",
      alt: "Property image 46",
      category: ""
    },
    {
      id: 47,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345732984-047_6.jpeg",
      alt: "Property image 47",
      category: ""
    },
    {
      id: 48,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345733603-048_7.jpeg",
      alt: "Property image 48",
      category: ""
    },
    {
      id: 49,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345734266-049_8.jpeg",
      alt: "Property image 49",
      category: ""
    },
    {
      id: 50,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345734987-050_3.jpeg",
      alt: "Property image 50",
      category: ""
    },
    {
      id: 51,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345735263-051_4.jpeg",
      alt: "Property image 51",
      category: ""
    },
    {
      id: 52,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345735655-052_5.jpg",
      alt: "Property image 52",
      category: ""
    },
    {
      id: 53,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345736032-053_2.jpeg",
      alt: "Property image 53",
      category: ""
    },
    {
      id: 54,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345736718-054_1.jpeg",
      alt: "Property image 54",
      category: ""
    },
    {
      id: 55,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345737489-055_12.jpeg",
      alt: "Property image 55",
      category: ""
    }
  ];

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "2 Bedrooms",
      description: "The kitchen and the high-end quality of the renovation finishings ",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345703648-001_0_mc3yc00gq9wx665lup.jpg"
    },
    {
      id: "section2",
      title: "2 Bathrooms",
      description: "",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345704688-002_14.jpeg"
    },
    {
      id: "section3",
      title: "1,205 sq ft",
      description: "Spacious living area with ample room for your lifestyle",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345705945-003_15.jpeg"
    },
    {
      id: "section4",
      title: "$749,900",
      description: "",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345707061-004_01TT39.jpeg"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Clanton Park",
    city: "Toronto",
    description: "Clanton Park in Toronto offers a balanced mix of culture, cuisine and convenience with easy TTC access and nearby cultural destinations. Residents benefit from diverse dining options and accessible green spaces such as Earl Bales Park, plus nearby amenities including the Aga Khan Museum and Sheppard Centre. The neighbourhood is well-suited to professionals seeking modern North York workspaces and families looking for parkland and transit connections.",
    highlights: [
      "Convenient subway access at Sheppard-Yonge Station for easy city exploration",
      "Proximity to Aga Khan Museum, featuring cultural exhibits and parks",
      "Nearby Sheppard Centre with diverse food court options and shopping",
      "North York neighbourhood offering modern workspaces and vibrant local amenities",
      "Close to Earl Bales Park for hiking, playgrounds and outdoor recreation"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "Sheppard Centre",
      distance: "",
      category: "shopping",
      icon: "ShoppingBag"
    },
    {
      id: 2,
      name: "Earl Bales Park",
      distance: "",
      category: "recreation",
      icon: "Leaf"
    },
    {
      id: 3,
      name: "Aga Khan Museum",
      distance: "",
      category: "education",
      icon: "School"
    },
    {
      id: 4,
      name: "WonWon Time",
      distance: "",
      category: "dining",
      icon: "Coffee"
    },
    {
      id: 5,
      name: "Chi's Kitchen",
      distance: "",
      category: "dining",
      icon: "Utensils"
    },
    {
      id: 6,
      name: "Sheppard Ave West at Bryant St West Side (bus stop)",
      distance: "",
      category: "transportation",
      icon: "Car"
    },
    {
      id: 7,
      name: "Rodney The Tree",
      distance: "",
      category: "recreation",
      icon: "Users"
    },
    {
      id: 8,
      name: "North York modern workspaces",
      distance: "",
      category: "business",
      icon: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "82/100",
      caption: "Very Walkable",
      icon: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "62/100",
      caption: "Good Transit",
      icon: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "53/100",
      caption: "Bikeable",
      icon: "Bicycle",
      color: "bg-indigo-500"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    date: "",
    startTime: "",
    endTime: "",
    registerLink: "",
    host: "",
    phone: "",
    email: "",
    ctaText: ""
  };

// packageItems configuration
export const packageItems = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 2 bedroom, 2 bathroom configuration with precise measurements.",
      icon: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Condo Apartment sales in Toronto.",
      icon: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "Public School District: Toronto District School Board (TDSB).\nCatholic School District: Toronto Catholic District School Board (TCDSB). \n\nDesignated Local Schools \nElementary: Faywood Arts-Based Curriculum School.\nSecondary: William Lyon Mackenzie Collegiate Institute (typical for the Clanton Park/North York area)",
      icon: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      icon: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      icon: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      icon: "Map"
    }
  ];

// property configuration
export const property = {
    name: "#415-701 Sheppard Ave West",
    address: {
      street: "#415-701 Sheppard Ave West",
      city: "Toronto",
      state: "Ontario",
      zip: "M3H 2S7",
      country: "Canada"
    },
    price: "$749,900",
    beds: 2,
    baths: 2,
    sqft: 1205,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    propertyType: "Condo Apartment",
    status: "For Sale",
    description: "South-facing balcony overlooking a greenbelt, and you can see the CN Tower from the balcony ",
    shortDescription: "2 BEDS + 2 BATHS",
    mainFeatures: [],
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345703648-001_0_mc3yc00gq9wx665lup.jpg",
    heroCaption: "South Balcony + Chef's Kitchen + Corner Unit = Your Perfect Condo Just Listed!",
    mapLocation: {
      lat: 43.6532,
      lng: -79.3832
    },
    virtualTourAvailable: true,
    virtualTourUrl: "https://www.winsold.com/tour/411706/branded/13839"
  };

// propertyFeatures configuration
export const propertyFeatures = [
    {
      id: 1,
      title: "The center island is movable or removable if the new owner does not want the island, and there is flooring underneath.",
      description: "The center island is movable or removable if the new owner does not want the island, and there is flooring underneath.",
      icon: "CheckCircle"
    },
    {
      id: 2,
      title: "There are two storage lockers included with this unit.",
      description: "There are two storage lockers included with this unit.",
      icon: "CheckCircle"
    },
    {
      id: 3,
      title: "Lots of light, very bright with lots of windows",
      description: "Lots of light, very bright with lots of windows",
      icon: "CheckCircle"
    },
    {
      id: 4,
      title: "South facing walkout balcony",
      description: "South facing walkout balcony",
      icon: "CheckCircle"
    },
    {
      id: 5,
      title: "New engineered flooring",
      description: "New engineered flooring",
      icon: "CheckCircle"
    }
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "/logo.svg",
    colors: {
      primary: "#D9A566"
    },
    footer: {
      copyrightText: "© 2025 #415-701 Sheppard Ave West. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change.",
      privacyPolicyUrl: "https://www.torontorealestate4u.com/site/privacy-terms"
    }
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "#415-701 Sheppard Ave West | Condo Apartment | Toronto",
    description: "South Balcony + Chef's Kitchen + Corner Unit = Your Perfect Condo Just Listed!",
    keywords: "condo apartment, Toronto real estate, 2 bedroom, 2 bathroom, $749,900",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1768345703648-001_0_mc3yc00gq9wx665lup.jpg",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://#415-701sheppardavewest.com"
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Joseph Bitton provided exceptional service and found us exactly what we were looking for in Toronto.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg",
      rating: 5
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Joseph Bitton presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
      rating: 5
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Joseph Bitton knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg",
      rating: 5
    }
  ];

